### PR TITLE
GitX 0.8.2 does not like first commits

### PR DESCRIPTION
**Pull request by RomainMuller**
Make a new repo in gitx.
Make a commit; observe how it will not let you look at it.
Make a second commit; see that it lets you look at that one normally but still will not let look at the first one.
(By looking at a commit I mean in the detail view.)

### CODE REVIEW

**Comment by RomainMuller** [comment]
Maybe that's because the first commit doesn't have parents and the parser expects one? I've witnessed the same behavior on an older version, but since I was looking after another bug I didn't really bother that one...

**Comment by dak180** [comment]
If I had to guess I would think that would be it.

**Comment by RomainMuller** [comment]
Ok, I found the source of the issue...

1 - is a bug in [GLFileView escapeHTML:] which causes a crash (kaboom).
2 - is that GitX tries to git diff-tree on the first commit, which has no parent and thus cannot diff-tree (empty result)

**Comment by RomainMuller** [comment]
Attached a commit that fixes a part of the issue (but sadly, not all of it). I would like to get input from @laullon or maybe @uncommon on how to address the fact git diff-tree will not work in that specific case, and what to do instead.

**Comment by RomainMuller** [comment]
Ok, completed the bug fix. It turns out adding --root to "git diff-tree" gets it to behave as we need.

**Comment by ericanderson** [comment]
This is funny. In 0.8.1 the newest commit couldn't be viewed. Now in 0.8.2 the oldest commit cannot be viewed.

**Comment by RomainMuller** [comment]
@ericanderson: After the commits I proposed there, or just using the 0.8.2 tagged code?

**Comment by ericanderson** [comment]
@RomainMuller: I didn't try your change, I just upgraded to 0.8.2 because I couldn't see the latest commit in 0.8.1 and just verified that yes, the oldest commit doesn't show in 0.8.2, while the newest one has been fixed.

**Comment by RomainMuller** [comment]
Okay. Hopefully my commits here will fix that.

**Comment by ericanderson** [comment]
Is it difficult to write unit tests for Cocoa apps?

**Comment by Uncommon** [comment]
Not really. I've been thinking GitX could use some more tests. I think the tricky part here would be setting up a system for having a temporary repository for each test. Once that was in place, you could do a lot.

**Comment by laullon** [comment]
Yes, I'm working on it

Sent from my iPhone
German Laullon
laullon@gmail.com

**Pull request merged**
