### PR TITLE
some important changes

### PR DESCRIPTION
**Pull request by apla**
hello.

i made some patches for review:
1) refresh commit history after commit
2) retain commit position in commit history after refreshing history (when selected latest commit, cursor changes to latest commit in refreshed history). ticket #281
3) when origin has mirror flag, push failed because command include refspec for commit (git push origin master) but this is unacceptable for git. in this case command must be (git push origin)
4) due to bug in parser, sometimes commit not displayed properly (at least when diff contains no changes in code, only permissions change)

my code not best, but it allow me to work with gitx without most annoying bugs.

thank you very much for maintaining good software!

### CODE REVIEW

**Comment by laullon** [comment]
Thanks... I'll review yours commits.

**Comment by SethMilliken** [comment]
FWIW, it looks like this patch will close "refresh switches from currently selected commit to most recent" https://github.com/laullon/gitx/issues/27

**Comment by laullon** [comment]
solved on 0.8.2

**Comment by laullon** [comment]
V0.8.2 beta is out http://gitx.posterous.com/gitx-l-v082-beta

**Pull request closed without merging**
