### PR TITLE
Two small changes that makes it much easier to work with multiple repositories

### PR DESCRIPTION
**Pull request by boxed**
- Save window size/position per repository
- Refresh all windows on focus and not just the selected one

### CODE REVIEW

**Comment by darconeous** [comment]
The default autorefresh behavior is rather obnoxious---updating everything no matter if things have changed or not, clearing out the search field every time I move to a non-GitX window and back again. We should consider only doing a refresh if things have actually changed.

**Comment by RomainMuller** [comment]
I agree with @darconeous on how the refresh should be less invasive.

Alternatively we could use the fsevents API to get notified of changes within the repository to know exactly what happened and refresh only when stuff happens, but this API isn't public (despite being rather stable since 10.5) and that is a fairly good reason not to...

**Comment by darconeous** [comment]
I don't mind doing a refresh on focus change as long as something really did change. FSEvents would be nice for continuous updates, but isn't necessary to make this feature less obnoxious.

**Comment by boxed** [comment]
I agree that the refresh behavior is annoying. I am switching back and forth a lot at work and it gets tired really fast. However this isn't strictly part of my change, it's a more fundamental change of the refresh code.

**Comment by RomainMuller** [comment]
FSEvents is a nice way to know if anything has changed actually. I agree it's probably overkill for the auto-refresh use-case however.

**Comment by darconeous** [comment]
c880de13d817a8f209a0d01e5012af4dfbfaadc6 helps make the auto-refresh logic behave much better. Feel free to add it to this pull request.

**Comment by darconeous** [comment]
Hmm, after further testing I don't think c880de13d817a8f209a0d01e5012af4dfbfaadc6 should be considered right now. I think a larger set of changes is required in order to get it working in a sane manner, as a lot of this code is a mess. In any case, I'll stop hijacking this pull request. If I come up with some better changes for this I'll add them to [my `auto-refresh-work` branch](http://github.com/darconeous/gitx/tree/auto-refresh-work/).

**Comment by boxed** [comment]
If you get something working nicely, let me know!

**Comment by laullon** [comment]
I'm refactoring all refresh methods... stay tuned.

**Comment by boxed** [comment]
This pull request had two fixes in it though, not just the refresh all change. The other is that window positions are saved per repository.

**Comment by laullon** [comment]
Can you fork&merge this changes over my last commit?

**Comment by boxed** [comment]
It's only those two lines you see in the diff for that changeset and also that you clear the autosave string on the window in the nib. I see now that the nib diff is all fucked up since I used a different version of xcode than you, so if I do that again it's probably gonna be the same...

**Pull request closed without merging**
