### PR TITLE
Show stash contents when selected in the sidebar

### PR DESCRIPTION
**Pull request by Uncommon**
Currently, the only thing you can do with stashes in the sidebar is right-click on them to pop/apply/drop. This change shows the selected stash diff in the right panel.

### CODE REVIEW

**Comment by laullon** [comment]
Good work!!!

**Comment by Uncommon** [comment]
Thanks :)

It was easier than I expected, since I was able to use the web history view as is. It seemed a bit sneaky to use it for something it wasn't quite intended for, with lots of sending messages to nil that happens to do the right thing. I'm tempted to refactor it so there's specifically a history version and a stash version.

**Comment by laullon** [comment]
I'm thinking on start a "new" GitX form scratch.... I don't like the actual source code...

**Comment by Uncommon** [comment]
I'm with you. I'm often finding that classes are too specialized when I'm trying to add a feature, and there's almost no source documentation. We could also do with some standardized code formatting.

**Comment by Uncommon** [comment]
It turns out I was a little hasty in submitting this. The commit/parent SHA links don't work, right-clicking the file paths doesn't show the right menu, and it only shows the unstaged part of the stash. I'm working on it.

**Pull request merged**
