### PR TITLE
New Features and Bugfixes

### PR DESCRIPTION
**Pull request by ghost**
1. Feature: Rename Remotes, Tags, Branches and RemoteBranches from the GUI
2. Feature: Delete RemoteBranch local and on the remote too
3. Bugfix:   DiscardHunk without action
4. Feature: Askpass-Dialog now on Top of all Windows
5. Feature: Change the Remote URL from the GUI
6. Bugfx:   Clone Repository with bare Option was not working
7. Bugfix:   Openpanel at "Clone to" appears only one time by awakeFromNib, then has no effect
8. Feature: Install GitCleanUpMechanism when Error occurs.
9. Bugfix:   Cleaning up GitRemote-List while adding a remote fails
10. Feature: GUI now able to commit merges
11. Bugfix:   Push Tags to Remotes
12. Feature: Delete Tag on Remotes too
13. Bugfix:   Show hidden Files on all NSOpenPanel
14. Feature: determinated ProgressIndicator while cloning a repo

### CODE REVIEW

**Comment by bfanger** [comment]
I like the new features, but there are some bugs in t 10 jan 2012 version.
- The submodules aren't showing anymore.
- The badges on the branches don't get updated (still showing "✓-1"  or a "✓") until i select/focus the branch.

**Comment by laullon** [comment]
good work Kyriakis.

**Comment by nicowald** [comment]
Just switched from 0d782b5fca4c0b710f53388bcf77abbd9541dbff to b9476a1bafc63a8f58648f66b93de258b8f9cfc2.
As bfanger already noted, the submodule list is always empty.
But even worse, when I create a local branch, remote is contacted to check that ref is not used already!?! First of all that makes no sense and secondly it results in beach balls when working offline. Connections to remotes should be initiated by user only when fetching, or pushing. This check remote first for all actions destroys the whole idea of git.

**Comment by ghost** [comment]
Hi together,
that's not my opinion about git. When you work on a bigger project like some navigation from bosch perhaps with more developers it causes problems when refs are created wich exist on remotes later by fetching or pushing.
Feel comfortable to change that.
Sorry bfanger for my late answer. I didn't develop in the part of submoduls, so I actually don't know, why this feature isn't working anymore. The next weeks I'm not able to go ahead on git. Too much work this days.
Robert

**Comment by jphalip** [comment]
I agree with @nicowald that systematically fetching the remote for every single operation is a problem. While I understand the reasons why @Kyriakis implemented that, I think this is not in line with the majority of usecases nor with how git is meant to be used, and therefore I think it should be changed to only contact the remote on fetch and push.

Now, I've looked into the code but I'm not sure if this new workflow is now tightly built into gitx or if if could easily be changed. @Kyriakis, could you please advise on how to make that change? Thanks!

**Comment by ghost** [comment]
Hi jphalip,
sorry for my late response. I understand the needs and reviewed the code.
You did a good job. There was one part left where the remotes where checked systematically by deleting a branch or tag.
I fixed it and make a pull request.
I hope, that this is  satisfying for you and nicowald.

**Pull request merged**
