### PR TITLE
A few more improvements

### PR DESCRIPTION
**Pull request by jphalip**

### CODE REVIEW

**Comment by jphalip** [comment]
I'm not sure why it created a separate pull request instead of updating #189.

This pull request contains 2 extra commits: 18d7767 and 8a9b962. Bizarrely those two don't show up on my github fork: https://github.com/jphalip/gitx

Am I missing something?

**Comment by laullon** [comment]
Please, check if all your change has been merged.
Thanks.

**Comment by jphalip** [comment]
@laullon Thanks for merging the pull request #189. I've asked github support to figure out why those 2 commits won't show up in my master branch on the github interface. Maybe it's possible already to pull them directly from here as well anyway. Thanks!

**Comment by jphalip** [comment]
Yes it worked, thank you!

**Pull request merged**
