### PR TITLE
A few small changes to better support Mac OS X Lion

### PR DESCRIPTION
**Pull request by roustem**
Currently using "gitx" in the command line will always show two GitX windows on 10.7.

It was happening because of the hidden preference. I added it to the Preferences window and also changed it to NO by default.

### CODE REVIEW

**Comment by RomainMuller** [comment]
I commented on commit 25b65ac, in that I think it should not be pulled in (OS-specific git ignores belong to the client side, not to the pseudo-centralized repository). It's only my own opinion however.

**Comment by roustem** [comment]
What are the drawbacks of having .DS_Store in the .gitignore?

**Comment by laullon** [comment]
Have you tested this changes on 10.6?

**Comment by RomainMuller** [comment]
@roustem Ultimately, none. However it is a good practice / philosophy to keep client-specific stuff on the client side. I would let the ultimate decision to @laullon.

**Comment by roustem** [comment]
Yes, it seems to work fine on 10.6.

**Pull request merged**
