### PR TITLE
Fixes for warnings and errors

### PR DESCRIPTION
**Pull request by Uncommon**
The current main branch (at d6098167) has a compile error and several warnings. This fixes them.

### CODE REVIEW

**Comment by Uncommon** [comment]
I removed the ppc architectures because I was getting link errors with libgit2.

Also, it looks like you can ignore the xib change in 6cef7908b84a9e4ca7d00839dbbc6c49989fb7dc because it looks like f45ca2791bbd02f2121d2b72b817785b4d27acfb does the same thing.

**Comment by RomainMuller** [comment]
If we could vote on pull requests, I'd vote for this one... I hate compilation warnings, and it's so easy to get rid of them!

**Comment by Uncommon** [comment]
Closed without comment?

**Comment by laullon** [comment]
Sorry... ;)

Most of this changes are already on master....

**Pull request closed without merging**
